export const CONFIG_DATA = 'CONFIG_DATA';
export const LOGIN_USER_DATA = 'LOGIN_USER_DATA';
export const DRIVER_VEHICLE_LIST = 'DRIVER_VEHICLE_LIST';
export const ORDERS = 'ORDERS';
export const NOTIFICATION = 'NOTIFICATION';
export const APP_TOUR = 'APP_TOUR';
export const NOTIFICATION_TOUR = 'NOTIFICATION_TOUR';
export const RESET_STORE = 'RESET_STORE';
